#!/bin/env bash
# starts your $EDITOR with all given arguments (if $EDITOR is empty: starts vi)
#
# (https://github.com/egnrse/v-editor)
# (by egnrse)

# shows the help menu
show_help() {
	if [ -z "$EDITOR" ]; then
		echo WARNING: \$EDITOR is not set, v-editor will try to use vi.
		echo ""
	fi
	echo "Usage:"
	echo "  v [options] [editor_args...]"
	echo ""
	echo "Options:"
	echo "  --vhelp       Show this help menu for v-editor and exit"
	echo "  --vversion    Show version info for v-editor and exit"
	echo "  (Must be the first option provided)"
	echo "  (All arguments not listed here are parsed as editor arguments and forwarded to the editor.)"
	echo ""
	echo "Editor Arguments:"
	echo "  Depends on the editor you use. You can try to use 'v -h' or 'v --help'."
}

# shows version infos
show_version() {
	echo "v-editor v0.0.1"
}

case "$1" in
	--vhelp)
		show_help
		exit 0
		;;
	--vversion)
		show_version
		exit 0
		;;
	-h|--help)
		echo "(To show the helpmenu for v-editor use 'v --vhelp'.)"
		;;
esac

# check if $EDITOR is empty
if [ -z "$EDITOR" ]; then
	echo "\$EDITOR is not set, using vi"
	# $@ stores all arguments given to this command
	vi "$@"
else
	"$EDITOR" "$@"
fi
