.\" v.1 - man page for v-editor
.TH V 1
.SH NAME
v \- wrapper for $EDITOR
.SH SYNOPSIS
.B v
[\fIoptions\fR] [\fIeditor_args\fR]
.SH DESCRIPTION
Start the program stored in the $EDITOR environment variable with all given arguments (by calling "$EDITOR $@"). If $EDITOR is empty, will try to start vi.
.\"
.SH OPTIONS
(Must be the first option provided. All arguments not listed here are parsed as editor arguments and forwarded to the editor.)
.TP
.B \-\-vhelp
Show help message and exit.
.TP
.B \-\-vtest
Show the command v-editor would try to execute and exit. (This will not fallback to vi, if there are any errors)
.TP
.B \-\-vversion
Show version info and exit.
.\"
.SH EDITOR_ARGS
Depends on the editor you use. You can try to use 'v -h' or 'v --help' to find them out.
.\"
.SH RETURN VALUES
Returns 255 if there was an error with the given editor ($EDITOR is empty or command was not found), else returns the return value of the editor.
.SH EXAMPLES
To use v-editor to open a file:
.IP "•"
Make sure you either have set the $EDITOR environment variable to an editor (eg. nvim) you have installed or have vi installed.
.IP "•"
Most editors (eg. vim, nvim) support opening a file given directly as an argument. If your editor does that too, open eg. \fItest.txt\fR with:
.IP
.EX
\fBv\fR \fItest.txt\fR
.EE
.\"
.PP
To find out what command is executed by v-editor (and get informed of possible errors):
.IP
.EX
\fBv\fR --vtest \fR
.EE
.\"
.SH AUTHOR
Elia Nitsche <nitscheelia@gmail.com>
.SH REPORTING BUGS
Report bugs at https://github.com/egnrse/v-editor/issues
.SH SEE ALSO
.BR vi (1),
.BR nvim (1)

